"""create core oil spill tables

Revision ID: aeaf1721c5f2
Revises: 
Create Date: 2026-09-06 13:40:56.829898

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'aeaf1721c5f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regions_geometry', 'regions', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=False)
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('imo_number', sa.String(length=20), nullable=True),
    sa.Column('vessel_type', sa.String(length=100), nullable=True),
    sa.Column('flag', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessels_imo_number'), 'vessels', ['imo_number'], unique=False)
    op.create_index(op.f('ix_vessels_name'), 'vessels', ['name'], unique=False)
    op.create_table('spills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('detection_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('polygon', geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('perimeter_km', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('estimated_age_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spills_centroid', 'spills', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index('idx_spills_polygon', 'spills', ['polygon'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spills_detection_time'), 'spills', ['detection_time'], unique=False)
    op.create_index(op.f('ix_spills_region_id'), 'spills', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spills_region_id'), table_name='spills')
    op.drop_index(op.f('ix_spills_detection_time'), table_name='spills')
    op.drop_index('idx_spills_polygon', table_name='spills', postgresql_using='gist')
    op.drop_index('idx_spills_centroid', table_name='spills', postgresql_using='gist')
    op.drop_table('spills')
    op.drop_index(op.f('ix_vessels_name'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_imo_number'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_index('idx_regions_geometry', table_name='regions', postgresql_using='gist')
    op.drop_table('regions')
    # ### end Alembic commands ###
